# Generated by Django 5.2.7 on 2025-10-28 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the exam, e.g., Midterm Test', max_length=100)),
                ('date', models.DateField(help_text='Exam date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created the exam', limit_choices_to={'role__in': ['TEACHER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.section')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.standard')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('name', 'standard', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(help_text='User who entered the marks', limit_choices_to={'role__in': ['TEACHER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='performance.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.subject')),
            ],
            options={
                'ordering': ['exam__date', 'subject__name'],
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
    ]
